{{- if (and .Values.serviceAccount.create .Values.serviceAccount.clusterRole.create) }}
{{- $saname := (include "app.serviceAccountName" .) }}
{{- $rname := (include "app.clusterRoleName" .) }}
{{- $rbname := (include "app.clusterRoleBindingName" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $rbname }}
  labels:
{{ include "app.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ $saname }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $rname }}
  apiGroup:  rbac.authorization.k8s.io
{{- end }}
