{{- $ingressDefaultHostname := (include "app.ingressDefaultHostname" .) }}
{{- $fullname := (include "app.fullname" .) }}
{{- if .Values.api.ingressInternal }}
{{- if .Values.api.ingressInternal.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $fullname }}-int"
  labels:
{{ include "app.labels" . | indent 4 }}
  annotations:
{{ include "app.ingressInternal.annotations" . | indent 4 }}
spec:
  rules:
{{- if .Values.api.ingressInternal.hostname }}
    - host: "{{ .Values.api.ingressInternal.hostname }}-int.{{ .Values.api.ingressInternal.dnsdomain }}"
{{- else }}
    - host: "{{ $ingressDefaultHostname }}-int.{{ .Values.api.ingressInternal.dnsdomain }}"
{{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
{{- end }}

{{- if .Values.api.ingressExternal -}}
{{- if .Values.api.ingressExternal.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $fullname }}"
  labels:
{{ include "app.labels" . | indent 4 }}
  annotations:
{{ include "app.ingressExternal.annotations" . | indent 4 }}
spec:
  rules:
{{- if .Values.api.ingressExternal.hostname }}
    - host: "{{ .Values.api.ingressExternal.hostname }}.{{ .Values.api.ingressExternal.dnsdomain }}"
{{- else }}
    - host: "{{ $ingressDefaultHostname }}.{{ .Values.api.ingressExternal.dnsdomain }}"
{{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}
                port:
                  number: {{ .Values.api.service.port }}
    {{- if and .Values.api.ingressExternal.additionalFqdn  (eq .Values.env "prod") }}
    - host: {{ .Values.api.ingressExternal.additionalFqdn | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}
                port:
                  number: {{ .Values.api.service.port }}
    {{- end }}
{{- end }}
{{- end }}
