{{ if .Values.serviceAccount.create }}
{{- $saname := (include "app.serviceAccountName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $saname }}-sa-token"
  annotations:
    kubernetes.io/service-account.name: "{{ $saname }}"
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/hook-weight: "-4"
type: kubernetes.io/service-account-token
{{ end }}
