{{ if .Values.serviceAccount.create }}
{{- $saname := (include "app.serviceAccountName" .) }}
apiVersion: v1
kind: ServiceAccount
secrets:
  - name: "{{ $saname }}-sa-token"
metadata:
  name: "{{ $saname }}"
  labels:
{{ include "app.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/hook-weight: "-5"
    {{- if .Values.serviceAccount.roleARN }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleARN | quote }}
    {{ end -}}
{{ end }}
